### ISSUE TITLE
[Request] AUR package?

### ISSUE THREAD

**Issue by Barbaross93** [Yvee1/hascard#10]
Hello,

Thank you so much for sharing this! This is an absolutely amazing program! I was wondering if it was possible to create an AUR package for Arch linux?

**Comment by Yvee1** [comment]
Hi, first of all thanks for the compliments haha

I've just taken a look at creating an AUR package. I don't have any experience with Arch linux or the AUR, so I might be wrong on some points but this is what I found. Only a few of the libraries I depend on are in the AUR which makes it impossible for my application to work solely on AUR dependencies. An alternative is to just depend on the Haskell package manager 'stack', and build the package just like building from source as in the [installation instructions](https://github.com/Yvee1/hascard#install-from-source). But this defeats the purpose of uploading to AUR I think; using the AUR just to install another package manager to install hascard definitely seems wrong.

So I'm afraid it is not possible/useful. Could you perhaps try installing from source with stack? On the internet I saw some issues with stack and arch-linux, adding the flag `--ghc-build=tinfo6` seems to help.

So you could do:
```bash
# Go to some directory
cd ~/Documents
git clone https://github.com/Yvee1/hascard.git
cd hascard
# install stack, skip if you've already got it
curl -sSL https://get.haskellstack.org/ | sh
# This command builds the application, and copies the executable to ~/.local/bin
# Building will take long the first time
stack install hascard --ghc-build=tinfo6
```

**Comment by Barbaross93** [comment]
Oh, you can just list stack as a make depend! So when the user finishes installing hascard, stack can get uninstalled. The reason I request this is so that I can update the hascard package itself rather than having to manually reinstall stack, clone the repo, build it, then uninstall stack. I've already installed it manually using the instructions listed on the readme, so I dont think the `--ghc-build=tinfo6` flag is necessary. The steps I listed earlier to install are definitely possible using the PKGBUILD system of Arch, but unfortunately I've never made a PKGBUILD and submitted to the AUR so I don't know how to do it myself. If I have time, I'll see if I can do it, but unfortunately I'm a bit behind with work, so I might not get around to it for a while. Here's a link to the PKGBUILD system of Arch, I think it should be pretty straightforward: https://wiki.archlinux.org/index.php/PKGBUILD This link explicitly talks about making a package, perhaps this would be more useful: https://wiki.archlinux.org/index.php/Creating_packages

**Comment by Yvee1** [comment]
Ah okay, so it _is_ useful even when just using stack behind the scenes, thanks for your explanation! The PKGBUILD file should be quite straightforward indeed, and I found an example one of a Haskell program which also builds with stack, so I'll see if I can make one.

I'll let you know how it goes!

**Comment by Yvee1** [comment]
Hmm, so I didn't realize that you need to run Arch Linux to be able to upload a package to the AUR (since you need `makepkg`) :(

I did make a [PKGBUILD already](https://gist.github.com/Yvee1/8028e3a471bf5ae7fea1838e37004327), it should work but again, I can't test it. So I can't do much for you I'm afraid...

If you want and have time it would be really great if you can [test the PKGBUILD](https://wiki.archlinux.org/index.php/Creating_packages#Testing_the_PKGBUILD_and_package) and [upload it to the AUR](https://wiki.archlinux.org/index.php/AUR_submission_guidelines) (you should change the maintainer comment in the PKGBUILD to your info). In case you take on the challenge and encounter any problems that you think I can help with, don't hesitate to ask!

**Comment by Barbaross93** [comment]
Finally got a chance to test it! Unfortunately, I get the following error:
```
==> Retrieving sources...
  -> Downloading hascard-0.2.1.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 23435    0 23435    0     0  47535      0 --:--:-- --:--:-- --:--:-- 47535
==> Validating source files with sha256sums...
    hascard-0.2.1.0.tar.gz ... FAILED
==> ERROR: One or more files did not pass the validity check!
```
I think you can tell the pkgbuild to ignore checksums if you'd like, otherwise I'm not sure how to go about fixing this

**Comment by Barbaross93** [comment]
A little more testing: Arch linux has a package called `pacman-contrib` which contains some useful tools. One of which is `updpkgsums`, which easily let me fix the above error. After that, I ended up having to change the build directory from `cd "$srcdir/${pkgname}"` to `cd "$srcdir/${pkgname}-${pkgver}"`. That was when I hit the roadblock with the following error:
```
Error parsing targets: The specified targets matched no packages.
Perhaps you need to run 'stack init'?
```
I run `stack init` and it gives this message at the end of its output (I'm assuming its the most important):
```
Selected resolver: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/10.yaml
Resolver 'https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/16/10.yaml' does not have all the packages to match your requirements.
    random-fu not found
        - hascard requires >=0.2.7 && <0.3

This may be resolved by:
    - Using '--omit-packages' to exclude mismatching package(s).
    - Using '--resolver' to specify a matching snapshot/resolver
```
I tried `stack build --resolver=nightly` after a cursory internet search, but it gives the same error message. I have a feeling that omitting random-fu is far from desirable, so I didn't try it. The random-fu package exists, its currently at 0.2.7.7 so it should work based on my limited understanding. I have no idea how to proceed from here =/

**Comment by Yvee1** [comment]
Hi,
Thank you for doing this!

The `Perhaps you need to run 'stack init'` error is strange, since it suggests there is no stack project in that directory. I checked this by downloading the .tar.gz file from hackage just like in the build instructions, and apparently there indeed is no stack project there... This is entirely my fault, I did not realize that this was the case. Apparently my way of uploading to hackage only uploads the minimum files for building the project and this does not contain stack files.

To solve this, instead of downloading the source from hackage, we can download from github instead. 
So I think changing the `source` to
```
source=(https://github.com/Yvee1/${pkgname}/archive/v${pkgver}.tar.gz)
```
should solve this issue.

Thanks for the detailed explanation of the steps you took

**Comment by Barbaross93** [comment]
Welp, looks like everything went smoothly! It's live on the AUR: https://aur.archlinux.org/packages/hascard/. You should add instructions to the README. Let me know if there's anything I should do to maintain it; it's my first time doing this so I have much to learn in terms of package maintenance!

**Comment by Yvee1** [comment]
Great! I'm actually just releasing 0.3.0.0 so I suppose you could update the version on the AUR already haha, maybe I should've mentioned it 😅. I'll update the instructions!

**Comment by Barbaross93** [comment]
Just did it! That was surprisingly easy! I might have to make PKGBUILDs for
everything sitting in my manually installed folder...
