### ISSUE TITLE
Feature request: images rendered with markdown

### ISSUE THREAD

**Issue by guppyfaced** [Yvee1/hascard#15]
## Feature
No functionality to render images in a card with markdown.

The current markdown format allows for a fantastic variety of ways to present questions and coupled to images would make the exercise more memorable.

## Suggestions
I'm not familiar with the Haskell ecosystem, but any form of image rendering in terminal, with markdown, would be more than adequate. 

[Imagemagick](https://en.wikipedia.org/wiki/ImageMagick) is a terminal-based rendering tool and I've found a Haskell implementation, [friday](https://github.com/RaphaelJ/friday).

## By the way
Love the flashcard tool, I think it's brilliant.

**Comment by Yvee1** [comment]
Hey, glad you like the application. I will look into adding image support, but rendering images in the terminal itself is only somewhat supported in a couple terminals emulators. I think opening an image viewer application to show the image might also work, but I will have to try that out. Adding such a feature would also make it possible to later add a way to write LaTeX in a card, by rendering it to an image, which could be nice perhaps.

I'll keep this issue up to date

**Comment by Yvee1** [comment]
I got around to implementing this a bit later than I had expected. But a kind of image support (along with some other small fixes) is present now in version 0.5. I implemented it close to how I originally suggested it in this issue. Any file can be included, and will then be opened in the default application for that file type. So e.g. an .html file could also be included, and will then be opened in a web browser. I also managed to get the LaTeX working.
For an explanation of how you can use it, look at [this section](https://github.com/Yvee1/hascard#including-files) in the readme.
