### ISSUE TITLE
Case insensitive fill-in answers?

### ISSUE THREAD

**Issue by apexatoll** [Yvee1/hascard#16]
Hi there, I just wanted to say that I love hascard - its fantastic

Is there any chance you could tweak how fill in answers work? (answers surrounded by underscores) A lot of the answers I implement are acronyms so it would be helpful if the user could enter them in case-insenstive. I would do this myself but I do not have any experience with Haskell (and have finals looming)

**Comment by Yvee1** [comment]
Hi, glad to hear you like it :)

I have thought about the case sensitivity before, and I agree that a setting for switching the case sensitivity would be a nice addition. I'm gonna try implementing it

**Comment by Yvee1** [comment]
I've added the setting and released a new version containing it. Let me know if it works for you, and I'll close the issue

**Comment by apexatoll** [comment]
Thank you so much for the fast response! Its all working perfectly on my side!
