### ISSUE TITLE
Add keys to scroll

### ISSUE THREAD

**Issue by GrimPixel** [Yvee1/hascard#25]
If the answer is long enough, the lower part will be invisible. Keys to scroll are needed.

**Comment by Yvee1** [comment]
I agree; I'm going to look into adding this. I'll keep the issue updated.

**Comment by Yvee1** [comment]
Adding this requires quite some effort. I plan on doing this in a couple of months when I have more time.

**Comment by Yvee1** [comment]
This has been implemented in version 0.6.0.1
