### ISSUE TITLE
libtinfo error when running binary

### ISSUE THREAD

**Issue by bound-variable** [Yvee1/hascard#29]
I'm on gentoo. Tried but failed to build from source. Running the binary produces:

`./hascard: /lib64/libtinfo.so.6: no version information available (required by ./hascard)`

The app does run though, so is this something to worry about?

**Comment by Yvee1** [comment]
If it works then there is no problem.
The terminfo library (libtinfo) is used by a library I depend on to determine terminal protocol. I'm afraid I don't know more about why it cannot find the version information in your case and what functionality depends on it.
