### ISSUE TITLE
Change the F1 key

### ISSUE THREAD

**Issue by GrimPixel** [Yvee1/hascard#31]
It is the key to open “Help” for MATE and maybe other desktop environments.

**Comment by Yvee1** [comment]
Do you have a suggestion for what key to change it to? The `h` key is used in parts for navigation (from the vim keybindings), so it is not a great option.

**Comment by GrimPixel** [comment]
I think it could be Tab.

**Comment by Yvee1** [comment]
Version 0.6.0.1 that I just released now uses Shift+Tab instead of F1. (Tab was already used for moving between open question 'gaps'.)
