### ISSUE TITLE
Characters disappeared in a pair of underscores

### ISSUE THREAD

**Issue by GrimPixel** [Yvee1/hascard#32]
For example
```
# question
1) dp = (∂p/∂T)_v dT + (∂p/∂v)_T dv
2) dv = (∂v/∂T)_p dT + (∂v/∂p)_T dp
3) dT = (∂T/∂p)_v dp + (∂T/∂v)_p dv
```
I got
```
1) dp = (∂p/∂T)T dv
2) dv = (∂v/∂T)T dp 
3) dT = (∂T/∂p)p dv
```
and I can't proceed to the next question.

**Comment by Yvee1** [comment]
Underscores are used for open questions (https://github.com/Yvee1/hascard#open-question). In the rare cases that you have underscores as part of your text you can escape them by adding backslashes.
In your case:
```
# question
1) dp = (∂p/∂T)\_v dT + (∂p/∂v)\_T dv
2) dv = (∂v/∂T)\_p dT + (∂v/∂p)\_T dp
3) dT = (∂T/∂p)\_v dp + (∂T/∂v)\_p dv
```

**Comment by GrimPixel** [comment]
Yes, underscore is in use. Formulae are better memorised in a different way.
