### ISSUE TITLE
Export to CSV

### ISSUE THREAD

**Issue by titorgla** [Yvee1/hascard#33]
Hi,
An option to export my custom flashcards (preferably as CSV) would make for a great utility

**Comment by Yvee1** [comment]
Thanks for the suggestion.
It would help to know your use case.
It is not clear to me that there is a useful CSV type format to export to that represents the different types of cards nicely and handles things like the CSV separator being part of the card text in a good way.
It may be easier for someone to write their own script that parses the markdown cards and exports them to the desired format.

**Comment by titorgla** [comment]
Appreciate the response
+ It would help to know your use case.
	+ I use other flashcard apps e.g. Anki, Quizzlet, Obsidian, ForgetMeNot, etc. most of which accept importing through CSV, a utility to convert my `hascard.md` flashcards to CSV would allow me to use it with the aforementioned apps which would be great.

+ It is not clear to me that there is a useful CSV type format to export to that represents the different types of cards nicely and handles things like the CSV separator being part of the card text in a good way.
	+ I don't know about other cards but I mainly use `Definition Cards` on all of my flashcards and sometimes `Open Question Cards`
	+ According to `RFC 4180` fields with embedded commas or double-quotes can be double quoted so it could be possible
	+ To the best of my knowledge hascard could drop the special characters, trim trailing and leading whitespaces and add a comma after newlines e.g.

```
# Question
Answer
---
# Question, Question
_Answer_
---
```
into
```
Question,Answer
"Question, Question",Answer
```

+ It may be easier for someone to write their own script that parses the markdown cards and exports them to the desired format.
	+ I did, with my limited knowledge of bash I've managed to macgyver a script that turns a simple `Definition Card` flashcard set into a simple CSV through RegEx and`gnuutils - tr`. It doesn't work half the time and I really don't have the time to create such a script
	+ It would make for a great utility for other users with similar use cases to have an export option builtin

Again great app, terminal flashcard apps are few and far between I just wish there's more, for the lack of a better word *cross-compatibility* with other flashcard apps

**Comment by Yvee1** [comment]
Thanks for the detailed response! I agree that it makes sense to offer such an export function, even if it is mainly useful for the definition and open cards. Someone else asked for import functionality before, which I implemented, and a corresponding export function makes sense... I'll put this on my list. I would like to find a block of time sometime soon™ in which I can delve back into the code and implement this mental list of improvements that has been building up ;)

**Comment by Yvee1** [comment]
Version 0.6.0.1 that I just released now has the requested export functionality for definition and open question cards.
You can call e.g. `hascard export input.txt output.txt` where input.txt contains the hascard cards and output.txt is the destination file. By default a comma is used as a separator between question and answer, and a newline between cards, but this can be configured. If one of the separators is part of the question or answer text the corresponding part is put between double quotes and any existing double quotes are 'escaped' by replacing them with two double quotes. See `hascard export --help` for more info.
