### ISSUE TITLE
homebrew formula

### ISSUE THREAD

**Issue by choucavalier** [Yvee1/hascard#4]
It would be nice to have a homebrew formula to install hascard on macOS easily

**Comment by Yvee1** [comment]
I agree that would be nice. I have taken a brief look at homebrew (I have no experience with it) and I read that they don't like self-submitted stuff (in [acceptable formulae](https://docs.brew.sh/Acceptable-Formulae)) so I can't add it to homebrew core without help. Apparently it's also possible to make you own taps which have no such restrictions, so I'll have a look at that and see what I can do. I'll keep this issue updated

**Comment by Yvee1** [comment]
I think I got it working! I don't have any computers with macOS so I can't test if it works. Would you mind checking if it works, and letting me know? You should be able to install it with `brew update && brew install Yvee1/tools/hascard`.
Thanks

**Comment by choucavalier** [comment]
Yay, that worked 😄 Thanks a lot. Maybe you can update the `Installation` section of the README with macOS instructions.

**Comment by Yvee1** [comment]
Great! I've updated the installation instructions
