### ISSUE TITLE
Can I ask about your terminal theme?

### ISSUE THREAD

**Issue by wookiist** [Yvee1/hascard#5]
Hello.
This is not an issue with your wonderful work.
I left an issue because I had a question with demo video.
I'm curious about the terminal theme from your demo video.
The "->" sign is so cute, can you tell me which theme you are using?

If this question had to be posted elsewhere, then sorry I will move it there!
Thanks in advance :)

**Comment by Yvee1** [comment]
Of course! I'm using [ohmyzsh](https://github.com/ohmyzsh/ohmyzsh) with the default robbyrussell theme which adds the little arrow. For the font and colors used you can look at the recordings/recording.yml file: https://github.com/Yvee1/hascard/blob/ed9b5fc07dd606560e2b2a39389dd4c264b805a0/recordings/recording.yml#L76-L110

**Comment by wookiist** [comment]
Thank you @Yvee1 !! 
Hope your work get more stars!!! ⭐️
